hge_plugin.o: hge_plugin.cpp hge181/include/hge.h ../../src/kllib.h
hge_plugin_font.o: hge_plugin_font.cpp ../../src/kllib.h \
  hge181/include/hgefont.h hge181/include/hge.h \
  hge181/include/hgesprite.h hge181/include/hgerect.h
hge_plugin_sprite.o: hge_plugin_sprite.cpp ../../src/kllib.h \
  hge181/include/hgeSprite.h hge181/include/hge.h \
  hge181/include/hgerect.h
