klinterpret.o: klinterpret.c klinterpret.h klsymtab.h klparser.h kllex.h \
  kllib.h
kllex.o: kllex.c kllex.h
kllib.o: kllib.c kllib.h klsymtab.h klinterpret.h klparser.h kllex.h
klparser.o: klparser.c klparser.h kllex.h
klsymtab.o: klsymtab.c klsymtab.h
