set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

" 不自动换行
set nowrap
" 设置tab为4
set tabstop=4
" 关闭GUI
set go=
" 没有备份
set nobackup
" 颜色主题
colorscheme desert
" 编辑C文件时tab为4
set cindent shiftwidth=4
" 显示行号
set number
" 设置每行为80字符
set tw=80 fo+=Mm
" 使用winManager管理fileExplorer和tagList
let g:winManagerWindowLayout='FileExplorer|TagList' 
nmap wm :WMToggle<cr>
" 按照语法折叠
set foldmethod=syntax
" 启动vim时不要自动折叠代码
set foldlevel=100 
" 开启自动补全
filetype plugin indent on
" 不显示补全预览窗口
set completeopt=longest,menu
" 设置替换tab为空格
set expandtab
