///
/// @file ScriptPropertyList.cpp
/// @author Kevin Lynx
///
//#include "stdafx.h"
#include "ScriptPropertyList.h"

DECLARE_SHAREDPRO_ARRAY (_s) = {
    "Armor",
    "ArmorEx",
    "ArmorExtraRatio",
    "ArmorExtraRatioEx",
    "ArmorPenetration",
    "ArmorPenetrationEx",
    "ArmorPenetrationExtraRatio",
    "ArmorPenetrationExtraRatioEx",
    "AttackInterval",
    "AttackSpeedAdd",
    "AttackSpeedLevel",
    "AttackSpeedLevelEx",
    "AttackSpeedLevelRatio",
    "AttackSpeedLevelRatioEx",
    "BearHealExtraRatio",
    "BearPhysicalDamageExtraRatio",
    "BearSpellDamageExtraRatio",
    "CauseHealExtraRatio",
    "CausePhysicalDamageExtraRatio",
    "CauseSpellDamageExtraRatio",
    "CriticalDamageIncrease",
    "CriticalDamageReduce",
    "CriticalLevel",
    "CriticalLevelEx",
    "CriticalLevelRatio",
    "CriticalLevelRatioEx",
    "CriticalRating",
    "CriticalRatingCompare",
    "CriticalRatingReduce",
    "CriticalReduceLevel",
    "CriticalReduceLevelEx",
    "CriticalReduceLevelRatio",
    "CriticalReduceLevelRatioEx",
    "DamageReduce",
    "DodgeLevel",
    "DodgeLevelEx",
    "DodgeLevelRatio",
    "DodgeLevelRatioEx",
    "DodgeProbability",
    "DodgeProbabilityCompare",
    "Focus",
    "FocusEndurance",
    "HitLevel",
    "HitLevelEx",
    "HitLevelRatio",
    "HitLevelRatioEx",
    "HitProbability",
    "HitProbabilityCompare",
    "Persistant",
    "PersistantEndurance",
    "PhysicalAttackPower",
    "PhysicalAttackPowerEx",
    "PhysicalAttackPowerExtraRatio",
    "PhysicalAttackPowerExtraRatioEx",
    "Resist",
    "ResistEndurance",
    "SpellAttackPower",
    "SpellAttackPowerEx",
    "SpellAttackPowerRatio",
    "SpellAttackPowerRatioEx",
    "SpellBreak",
    "SpellPenetration",
    "SpellPenetrationEx",
    "SpellPenetrationExtraRatio",
    "SpellPenetrationExtraRatioEx",
    "SpellPotential",
    "SpellPotentialEx",
    "SpellPotentialRatio",
    "SpellPotentialRatioEx",
    "SpellResisitence",
    "SpellResisitenceEx",
    "SpellResisitenceRatio",
    "SpellResisitenceRatioEx",
    "SpellSpeed",
    "SpellSpeedLevel",
    "SpellSpeedLevelEx",
    "SpellSpeedLevelRatio",
    "SpellSpeedLevelRatioEx",
    "SpellToughness",
    "SpellToughnessEx",
    "SpellToughnessRatio",
    "SpellToughnessRatioEx",
    "Stable",
    "StableEndurance",
    "Will",
    "WillEndurance",
    NULL
};

SharedProArray SP_Get ()
{
    return _s;
}

